env: 'CartPole-v0'
gamma: 0.9

model:
  n_hiddens: 256

train:
  lr: 0.1
  n_episode: 400
  device_ids: 5
  batch_size: 64
  buffer_size: 100000

test:
  n_episode: 100

greedy:
  epsilon_start: 0.95
  epsilon_end: 0.01
  epsilon_decay: 300
