#env: 'CartPole-v0'
#env: 'CartPole-v1'
env: 'Acrobot-v1'
gamma: 0.9

model:
  n_hiddens: 256

train:
  lr: 0.0002
  n_episode: 200
  device_ids: 4
  batch_size: 128
  buffer_size: 100000
  tau: 0.8
  grad_clip: 1.0
  target_update: 2

test:
  n_episode: 100

greedy:
  epsilon_start: 0.95
  epsilon_end: 0.01
  epsilon_decay: 2000
